---
# tasks file for while_true_do.sys_update

- name: Manage Dependency Packages
  package:
    name: "{{ wtd_sys_update_dep_packages }}"
    state: "{{ wtd_sys_update_dep_packages_state }}"
  become: true
  tags:
    - package
    - security
    - system
    - update
    - upgrade

- name: Update System Packages
  yum:
    name: "*"
    state: latest
    update_cache: true
    security: "{{ wtd_sys_update_security_only }}"
    update_only: "{{ wtd_sys_update_update_only }}"
  become: true
  tags:
    - package
    - security
    - system
    - update
    - upgrade

- name: Check System Reboot
  command: needs-restarting -r
  ignore_errors: true
  register: wtd_sys_update_reboot_check
  changed_when: wtd_sys_update_reboot_check.rc == 1 or
                wtd_sys_update_reboot_forced
  failed_when: wtd_sys_update_reboot_check.rc != 1 and
               wtd_sys_update_reboot_check.rc != 0
  become: true
  when: wtd_sys_update_reboot_enabled or
        wtd_sys_update_reboot_forced
  notify: Reboot System
  tags:
    - package
    - reboot
    - security
    - system
    - update
    - upgrade
